#Drugs by OhYea777

#FOR FULL INFORMATION ON CONFIGURATION SEE - http://dev.bukkit.org/server-mods/drugs/pages/configuration/

# The Option will contain many settings, for now it
# just contains the:
# - Prefix
# This is what goes before the message in-game
# - Check_For_Updates
# This enables update checking when you join the server
# The:
# - UseCustomPerms
# Toggles the ability to use custom perms for each drug
Options:
  Prefix: "&0(&aDrugs&0)&f"
  Check_For_Updates: true
  UseCustomPerms: true
# This is the important part, here you can customize
# what the drugs are, their effects and strengths
# It uses the following format:
# Drugs:
#   <item id of drug>:
#     Commands:
#     - <command, don't include the '/'>
#     Random_Effects:
#       <effect name>:
#         Chance: <percent chance, don't include the '%'>
#         Duration: <duration of effect, in seconds>
#         Strength: <strength of effect, 0 is a strength of 1 etc.
#     Options:
#       Nickname: <nickname of drug>
#       Usage_Message: <custom usage message>
#		Permission: <custom permission>
# If you're using an item with a data value simply
# set it up like below MAKE SURE IT HAS THE '' or
# you WILL get errors
# Drugs:
#   '<id>:<value>':
#     Commands:
#     - <command, don't include the '/'>
#     Effects:
#       <effect name>:
#         Duration: <duration of effect, in seconds>
#         Strength: <strength of effect>
#     Random_Effects:
#       <effect name>:
#         Chance: <percent chance, don't include the '%'>
#         Duration: <duration of effect, in seconds>
#         Strength: <strength of effect, 0 is a strength of 1 etc.
#     Options:
#       Nickname: <nickname of drug>
#       Usage_Message: <custom usage message>
Drugs:
  353:
    Commands:
    - burn {player} 1
    Effects:
      Speed:
        Duration: 10
        Strength: 5
      Haste:
        Duration: 10
        Strength: 5    
      Strength:
        Duration: 10
        Strength: 1
      Poison:
        Duration: 20
        Strength: 5
    Options:
      Nickname: Methamphetamine
      Usage_Message: You have just smoked {drug}
  '351:2':
    Effects:
      Hunger:
        Duration: 10
        Strength: 2
      Slow:
        Duration: 10
        Strength: 2
      SlowDigging:
        Duration: 10
        Strength: 2
    Random_Effects:
      Speed:
        Chance: 10
        Duration: 10
        Strength: 1
    Options:
      Nickname: Weed
      Usage_Message: You have just smoked {drug}
  39:
    Random_Effects:
      Nausea:
        Chance: 50
        Duration: 10
        Strength: 10
    Options:
      Nickname: Shrooms
      Usage_Message: You have just eaten {drug}
# You can configure these messages to your liking
# You can also use colour codes in these messages,
# for a list of colour codes, see - http://ess.khhq.net/mc/
# Use {drug} to get the name of the drug used, doesn't
# work with "Reload"
Message:
  Reload: "Config Reloaded!"
  No_Perm: "&4You Don't Have Permission!"
  Drug_Use: "You Have Just Used {drug}"